### register

POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name":"test user",
    "email":"test@gmail.com",
    "password":"1234"
}

### login

POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"1234"
}
### get user profile

GET  http://localhost:5000/api/user/

### get all users

GET  http://localhost:5000/api/user/all

### update a user

PUT  http://localhost:5000/api/user/67c2eef2e8d735c3c5dbecd0
Content-Type: application/json

{
    "name":"test user",
    "password":"1234",
    "age":"21"
}
### delete a user
DELETE http://localhost:5000/api/user/67c2eef2e8d735c3c5dbecd0







